import test from 'node:test';
import assert from 'node:assert/strict';
import { calculateLiuyao, liuyaoCalendar, palaceForHexagram, relativeForElement } from '../src/liuyao/index.ts';
import { hexagram } from '../src/core/hexagrams.ts';
import { wallTimeToInstant } from '../src/core/calendar.ts';
import type { Element, Line } from '../src/core/types.ts';
const at=(wall:string,timeZone='Asia/Shanghai')=>({capturedAt:wallTimeToInstant(wall,timeZone),timeZone,details:{}});
const env=at('2024-02-10T12:00');
const cast=(values:readonly number[],environment=env)=>calculateLiuyao({question:'对照例盘',values,environment});

test('人工乾静卦例：HKO甲辰日、寅月，六亲/纳甲/世应/六神/旬空完整',()=>{
  const r=cast([7,7,7,7,7,7]);
  assert.deepEqual([r.primary.number,r.changed.number,r.calendar.dayGanzhi,r.calendar.monthBranch],[1,1,'甲辰','寅']);
  assert.deepEqual(r.calendar.voidBranches,['寅','卯']);assert.equal(r.calendar.xun,'甲辰旬');
  assert.deepEqual(r.lines.map(x=>[x.najia,x.element,x.relative,x.spirit,x.role,x.void]),[
    ['甲子','水','子孙','青龙','',false],['甲寅','木','妻财','朱雀','',true],['甲辰','土','父母','勾陈','应',false],
    ['壬午','火','官鬼','螣蛇','',false],['壬申','金','兄弟','白虎','',false],['壬戌','土','父母','玄武','世',false]
  ]);assert.deepEqual(r.movingLines,[]);
});
test('古籍屯之震形态：第四老阴/第五老阳；纳甲按下震上坎独立装配',()=>{
  const r=cast([7,8,8,6,9,8],at('2024-08-08T12:00'));
  assert.deepEqual([r.primary.number,r.changed.number],[3,51]);
  assert.deepEqual([r.palace.name,r.palace.stage,r.palace.shi,r.palace.ying],['坎','二世',2,5]);
  assert.deepEqual([r.calendar.monthBranch,r.calendar.dayGanzhi],['申','甲辰']);
  assert.deepEqual(r.movingLines,[4,5]);
  assert.deepEqual(r.lines.map(x=>x.najia),['庚子','庚寅','庚辰','戊申','戊戌','戊子']);
  assert.deepEqual(r.lines.map(x=>x.relative),['兄弟','子孙','官鬼','父母','官鬼','兄弟']);
  assert.deepEqual(r.lines.map(x=>x.changed.najia),['庚子','庚寅','庚辰','庚午','庚申','庚戌']);
  assert.equal(r.lines[3]!.changed.relative,'妻财'); // 沿本卦坎水，不随震木改六亲.
});
test('古籍艮之颐形态重放：两动爻同时翻转，各爻变卦字段保留',()=>{
  const r=cast([6,8,9,8,8,7]);
  assert.deepEqual([r.primary.number,r.changed.number],[52,27]);
  assert.deepEqual(r.movingLines,[1,3]);
  assert.deepEqual([r.lines[0]!.najia,r.lines[0]!.relative,r.lines[0]!.changed.najia,r.lines[0]!.changed.relative],['丙辰','兄弟','庚子','妻财']);
  assert.deepEqual([r.lines[2]!.najia,r.lines[2]!.relative,r.lines[2]!.changed.najia,r.lines[2]!.changed.relative],['丙申','子孙','庚辰','兄弟']);
});
test('八宫64卦按原书独立宫序表核对，含游魂与归魂世应',()=>{
  // 增删卜易/3/八卦各宫全图: independent literal oracle, not generated by palace code.
  const groups:readonly [string,number[]][]=[
    ['乾',[1,44,33,12,20,23,35,14]],['兑',[58,47,45,31,39,15,62,54]],
    ['离',[30,56,50,64,4,59,6,13]],['震',[51,16,40,32,46,48,28,17]],
    ['巽',[57,9,37,42,25,21,27,18]],['坎',[29,60,3,63,49,55,36,7]],
    ['艮',[52,22,26,41,38,10,61,53]],['坤',[2,24,19,11,34,43,5,8]]
  ];
  const oracle=new Map(groups.flatMap(([name,ids])=>ids.map((number,i)=>[number,{name,stageIndex:i,shi:[6,1,2,3,4,5,4,3][i]!,ying:[3,4,5,6,1,2,1,6][i]!}] as const)));
  for(let upper=1;upper<=8;upper++)for(let lower=1;lower<=8;lower++){
    const h=hexagram(upper,lower),p=palaceForHexagram(h),e=oracle.get(h.number)!;
    assert.deepEqual([p.name,p.stageIndex,p.shi,p.ying],[e.name,e.stageIndex,e.shi,e.ying],h.title);
  }
});
test('八纯纳甲独立表核对，包括乾坤内外干与阴卦逆支',()=>{
  const expected=[['甲子','甲寅','甲辰','壬午','壬申','壬戌'],['丁巳','丁卯','丁丑','丁亥','丁酉','丁未'],
    ['己卯','己丑','己亥','己酉','己未','己巳'],['庚子','庚寅','庚辰','庚午','庚申','庚戌'],
    ['辛丑','辛亥','辛酉','辛未','辛巳','辛卯'],['戊寅','戊辰','戊午','戊申','戊戌','戊子'],
    ['丙辰','丙午','丙申','丙戌','丙子','丙寅'],['乙未','乙巳','乙卯','癸丑','癸亥','癸酉']];
  for(let i=1;i<=8;i++)assert.deepEqual(cast(hexagram(i,i).lines.map(x=>x?7:8)).lines.map(x=>x.najia),expected[i-1]);
});
test('三枚硬币6/7/8/9严格对应阴阳与动静，六老阳/六老阴全变',()=>{
  for(const value of [6,7,8,9])for(let position=0;position<6;position++){
    const v=[7,7,7,7,7,7];v[position]=value;const r=cast(v),x=r.lines[position]!;
    assert.equal(x.yinYang,value%2);assert.equal(x.moving,value===6||value===9);
    assert.equal(x.changed.yinYang,value===6?1:value===9?0:value%2);
  }
  assert.deepEqual([cast([9,9,9,9,9,9]).primary.number,cast([9,9,9,9,9,9]).changed.number],[1,2]);
  assert.deepEqual([cast([6,6,6,6,6,6]).primary.number,cast([6,6,6,6,6,6]).changed.number],[2,1]);
});
test('所有64种动爻组合均同时翻转，静爻不变',()=>{
  for(let mask=0;mask<64;mask++){
    const values=Array.from({length:6},(_,i)=>mask&(1<<i)?9:7),r=cast(values);
    assert.deepEqual(r.changed.lines,values.map(x=>x===9?0:1) as Line[]);
    assert.equal(r.movingLines.length,values.filter(x=>x===9).length);
  }
});
test('香港天文台2026十二节原始时刻对照：计算偏差小于90秒，前后5分钟月建切换',()=>{
  // Exact HKT minute values from official 24SolarTerms_2026.xml (not vendor output).
  const fixtures=[['小寒','01-05T16:23','丑'],['立春','02-04T04:02','寅'],['惊蛰','03-05T21:59','卯'],['清明','04-05T02:40','辰'],
    ['立夏','05-05T19:49','巳'],['芒种','06-05T23:48','午'],['小暑','07-07T09:57','未'],['立秋','08-07T19:43','申'],
    ['白露','09-07T22:41','酉'],['寒露','10-08T14:29','戌'],['立冬','11-07T17:52','亥'],['大雪','12-07T10:53','子']];
  for(const [name,wall,branch] of fixtures){
    const official=Date.parse(`${'2026-'+wall}:00+08:00`);
    const make=(time:number)=>liuyaoCalendar({...env,capturedAt:new Date(time).toISOString()});
    const before=make(official-300000),after=make(official+300000);
    assert.equal(before.nextJie.name,name);assert.equal(after.previousJie.name,name);
    assert.ok(Math.abs(Date.parse(after.previousJie.instant)-official)<90000,name);
    assert.notEqual(before.monthBranch,branch);assert.equal(after.monthBranch,branch);
  }
});
test('恰好交节起新月建；相同瞬间换时区只改变日界与展示，不改变月建',()=>{
  const before=liuyaoCalendar(at('2026-02-04T03:55')),boundary=Date.parse(before.nextJie.instant);
  assert.equal(liuyaoCalendar({...env,capturedAt:new Date(boundary-1000).toISOString()}).monthBranch,'丑');
  assert.equal(liuyaoCalendar({...env,capturedAt:new Date(boundary).toISOString()}).monthBranch,'寅');
  const ny=liuyaoCalendar({...env,capturedAt:new Date(boundary).toISOString(),timeZone:'America/New_York'});
  assert.equal(ny.monthBranch,'寅');assert.equal(ny.previousJie.instant,before.nextJie.instant);
  assert.equal(ny.localDate,'2026-02-03');
});
test('日辰民用零点换日，23点不提前；中气/农历初一不改变月建',()=>{
  assert.equal(liuyaoCalendar(at('2024-02-10T22:59')).dayGanzhi,'甲辰');
  assert.equal(liuyaoCalendar(at('2024-02-10T23:00')).dayGanzhi,'甲辰');
  assert.equal(liuyaoCalendar(at('2024-02-11T00:00')).dayGanzhi,'乙巳');
  assert.equal(liuyaoCalendar(at('2024-02-09T12:00')).monthBranch,'寅');
  assert.equal(liuyaoCalendar(at('2024-02-10T12:00')).monthBranch,'寅');
  assert.equal(liuyaoCalendar(at('2024-02-19T12:00')).monthBranch,'寅');
});
test('六旬空表与六神十日干表核对，不混用年份日干',()=>{
  const xuns=[['2024-02-10','甲辰旬',['寅','卯']],['2024-02-20','甲寅旬',['子','丑']],['2024-03-01','甲子旬',['戌','亥']],
    ['2024-03-11','甲戌旬',['申','酉']],['2024-03-21','甲申旬',['午','未']],['2024-03-31','甲午旬',['辰','巳']]] as const;
  for(const [day,xun,voids] of xuns){const c=liuyaoCalendar(at(`${day}T12:00`));assert.equal(c.xun,xun);assert.deepEqual(c.voidBranches,voids);}
  const spirits=['青龙','青龙','朱雀','朱雀','勾陈','螣蛇','白虎','白虎','玄武','玄武'];
  for(let i=0;i<10;i++)assert.equal(cast([7,7,7,7,7,7],at(`2024-02-${10+i}T12:00`)).lines[0]!.spirit,spirits[i]);
});
test('本卦宫五行生成六亲关系正确，冻结输出并拒绝非法输入',()=>{
  assert.deepEqual(['金','水','木','火','土'].map(e=>relativeForElement('金',e as Element)),['兄弟','子孙','妻财','官鬼','父母']);
  const values=[7,8,7,8,7,8],environment={...env,details:{canary:'original'}},r=cast(values,environment);
  values[0]=9;environment.details.canary='changed';assert.equal(r.input.values[0],7);assert.equal(r.input.environment.details.canary,'original');
  assert.ok(Object.isFrozen(r.lines[0]!.changed));
  for(const bad of [[7,7,7],[7,7,7,7,7,10],[7,7,7,7,7,6.5],[7,7,7,7,7,NaN]])assert.throws(()=>cast(bad));
  assert.throws(()=>cast([7,7,7,7,7,7],{...env,capturedAt:'bad'}));
  assert.throws(()=>calculateLiuyao({question:' ',values:[7,7,7,7,7,7],environment:env}));
});
