import {useState,useEffect} from 'react';
import type {MethodPageState} from './method-controller.ts';
import type {NewMethodId} from '../shared/modules.ts';
import {moduleInfo} from '../shared/modules.ts';
import type {XiaoliuResult} from '../xiaoliu/types.ts';
import type {LiuyaoResult} from '../liuyao/types.ts';
import type {LenormandResult} from '../lenormand/types.ts';
import {lenormandAssets} from '../lenormand/assets.ts';
import type {MemoryPageState} from './memory-controller.ts';
import {BackgroundControls} from './MemoryPanel.tsx';
import {readingIsBusy} from '../shared/protocol.ts';
import {Conversation,formatConversationCopy} from './Conversation.tsx';
import type {Translate} from './locales.ts';
import {localTimestamp} from '../core/calendar.ts';

export interface MethodActions {
  onStart:()=>Promise<boolean>;onLocal:(endpoint:string,payload?:object)=>Promise<boolean>;onInterpret:()=>Promise<boolean>;onFollowup:(question:string)=>Promise<boolean>;onCancel:()=>Promise<boolean>;onRefresh:()=>Promise<void>;onCheckpoint:()=>Promise<void>;onDraft:(patch:Partial<MethodPageState['draft']>)=>void;
}
export interface MethodPageProps extends MethodActions {moduleId:NewMethodId;state:MethodPageState;memory?:MemoryPageState;onOpenMemory?:()=>void;t:Translate}

const methodCopy={
  xiaoliu:{caption:'六宫循行 · 月、日、时',input:'起课之前',empty:'循六位，落一宫',description:'由农历月、日与时辰依次顺数，保留三阶段落宫与完整计算约定。',steps:['写下所问之事','选择起课时间','查看月宫、日宫与时宫']},
  lenormand:{caption:'植物小牌 · 由象成句',input:'抽牌之前',empty:'让相邻的象，组成一句话',description:'选择三张连读或五张对照，以中牌为主题，结合相邻组合与镜像关系。',steps:['写下问题，选择排列','按顺序选择背牌','揭示中牌与组合线索']},
  liuyao:{caption:'三枚铜钱 · 六爻成卦',input:'投币之前',empty:'六次投币，自下而上',description:'逐爻记录三币和值，再查看本卦、变卦、世应、六亲与旬空。',steps:['写下问题与起卦时间','投币或手录六个和值','查看完整纳甲与动爻']},
} as const;

/** Decorative method symbols are kept separate from calculated result diagrams. */
function MethodArtwork({id}:{id:NewMethodId}){
  if(id==='xiaoliu')return <svg className="wx-method-art" viewBox="0 0 240 190" fill="none" aria-hidden="true"><circle cx="120" cy="95" r="70" className="wx-art-soft"/><circle cx="120" cy="95" r="58"/><path d="M120 25 181 60 181 130 120 165 59 130 59 60Z"/><path d="m120 37 50 29v58l-50 29-50-29V66Z" className="wx-art-soft"/><path d="M120 25V49M181 60l-21 12M181 130l-21-12M120 165v-24M59 130l21-12M59 60l21 12"/>{[[120,25],[181,60],[181,130],[120,165],[59,130],[59,60]].map(([x,y],i)=><g key={i}><circle cx={x} cy={y} r="14" className="wx-art-node"/><text x={x} y={(y??0)+4}>{i+1}</text></g>)}<path d="M100 95c10-21 31-23 41-2-10 23-31 22-41 2Z"/><path d="M90 103c22 8 42 9 61-9M103 87l16 23" className="wx-art-soft"/><circle cx="120" cy="95" r="5" className="wx-art-solid"/></svg>;
  if(id==='lenormand')return <svg className="wx-method-art" viewBox="0 0 240 190" fill="none" aria-hidden="true"><rect x="44" y="43" width="65" height="105" rx="7" transform="rotate(-14 44 43)" className="wx-art-soft"/><rect x="136" y="28" width="65" height="105" rx="7" transform="rotate(14 136 28)" className="wx-art-soft"/><rect x="83" y="24" width="76" height="132" rx="7" className="wx-art-node"/><rect x="90" y="31" width="62" height="118" rx="4" className="wx-art-soft"/><path d="M120 136V61M120 112c-24-1-34-19-31-34 19 0 31 14 31 34ZM120 97c24-1 34-19 31-34-19 0-31 14-31 34ZM120 79c-16-6-20-17-16-27 14 3 20 13 16 27Z"/><path d="M115 136h10M111 44h18" className="wx-art-soft"/><circle cx="120" cy="43" r="2" className="wx-art-solid"/><path d="M43 164h154M69 169h101" className="wx-art-soft"/></svg>;
  return <svg className="wx-method-art" viewBox="0 0 240 190" fill="none" aria-hidden="true"><path d="M38 141c29 24 132 24 164 0M54 160h132" className="wx-art-soft"/>{[{x:81,y:104,r:38},{x:159,y:104,r:38},{x:120,y:58,r:39}].map(({x,y,r},i)=><g key={i}><circle cx={x} cy={y} r={r} className="wx-art-node"/><circle cx={x} cy={y} r={r-7} className="wx-art-soft"/><rect x={x-10} y={y-10} width="20" height="20"/><path d={`M${x-21} ${y-3}v7M${x+21} ${y-3}v7M${x-3} ${y-22}h6M${x-3} ${y+22}h6`} className="wx-art-soft"/></g>)}<path d="M31 58h20M41 48v20M194 49h14M201 42v14" className="wx-art-soft"/></svg>;
}

function LiuyaoDiagram({result,changed=false}:{result:LiuyaoResult;changed?:boolean}){
  const hex=changed?result.changed:result.primary,palace=changed?result.changedPalace:result.palace;
  return <section className={`wx-hex-card${changed?'':' wx-hex-card-primary'}`} aria-label={`${changed?'变卦':'本卦'} ${hex.title}`}><p className="wx-method-kicker">{changed?'变卦':'本卦'} · 第 {hex.number} 卦</p><h3>{hex.title}</h3><div className="wx-hex-lines" role="img" aria-label={[...result.lines].reverse().map(line=>`${line.position}爻${(changed?line.changed:line).yinYang?'阳':'阴'}${(changed?line.changed:line).role}`).join('，')}>{[...result.lines].reverse().map(line=>{const actual=changed?line.changed:line;return <div key={line.position} className={`wx-hex-row${line.moving&&!changed?' wx-hex-row-moving':''}`}><span className="wx-hex-position">{line.position}</span><span className={`wx-hex-bar${actual.yinYang?'':' wx-hex-bar-yin'}`}><i/>{!actual.yinYang&&<i/>}</span><span className="wx-hex-role">{actual.role}{line.moving&&!changed?<b>{line.yinYang?'○':'×'}</b>:null}</span></div>;})}</div><p className="wx-method-caption">{palace.name}宫{palace.element} · {palace.stage}</p><p className="wx-method-caption">世{palace.shi}应{palace.ying} · 上{hex.upper.name}下{hex.lower.name}</p></section>;
}

function MethodResult({id,result}:{id:NewMethodId;result:unknown}){
  if(id==='xiaoliu'){
    const r=result as XiaoliuResult;
    return <><p className="wx-method-kicker">农历 {r.lunar.leapMonth?'闰':''}{r.lunar.month}月{r.lunar.day}日 · {r.lunar.hourBranch}时</p><div className="wx-six-palaces">{[r.monthPalace,r.dayPalace,r.hourPalace].map((palace,i)=><article key={i} className={i===2?'wx-palace-final':''}><span className="wx-palace-order" aria-hidden="true">0{i+1}</span><small>{['月宫','日宫','时宫 · 落宫'][i]}</small><h3>{palace.name}</h3><p>{palace.element} · {palace.spirit}</p><p className="wx-palace-keywords">{palace.keywords.join(' · ')}</p></article>)}</div><section className="wx-palace-meaning"><p className="wx-method-kicker">本次落宫</p><h2>{r.name} · {r.element}</h2><p>{r.meaning}</p></section><details><summary>六位顺数过程与约定</summary><ol>{r.steps.map((step,i)=><li key={i}>{step}</li>)}</ol>{r.conventions.map((line,i)=><p key={i}>{line}</p>)}</details></>;
  }
  if(id==='lenormand'){
    const r=result as LenormandResult;
    return <><p className="wx-method-kicker">{r.spread.name} · 中牌主题：{r.center.card.name}</p><div className={`wx-small-cards wx-small-cards-${r.cards.length}`}>{r.cards.map(({card,positionIndex,positionLabel})=><article key={card.id} className={positionIndex===r.center.positionIndex?'wx-card-center':''}><small>{positionIndex+1} · {positionLabel}{positionIndex===r.center.positionIndex?' · 中牌':''}</small><img src={lenormandAssets[card.id]} alt={`${card.id} ${card.name} 原创牌面`}/><h3>{card.id} · {card.name}</h3><p className="wx-card-keywords">{card.keywords.join(' · ')}</p><p>{card.symbolism}</p><p className="wx-card-advice">{card.advice}</p></article>)}</div><section className="wx-card-theme"><p className="wx-method-kicker">中牌 · 第 {r.center.positionIndex+1} 位</p><h2>{r.center.card.name} · 本组主题</h2><p>{r.center.card.symbolism}</p></section><section className="wx-card-combinations"><h3>相邻组合</h3><div className="wx-pair-list">{r.adjacentPairs.map((pair,i)=><div key={i} className="wx-pair"><small>位置 {pair.indices.map(index=>index+1).join(' → ')}</small><h4>{pair.phrase}</h4><p>{pair.explanation}</p></div>)}</div>{!!r.mirrors.length&&<><h3>镜像对照</h3><div className="wx-pair-list">{r.mirrors.map((pair,i)=><div key={i} className="wx-pair"><small>位置 {pair.indices.map(index=>index+1).join(' ↔ ')}</small><h4>{pair.phrase}</h4><p>{pair.explanation}</p></div>)}</div></>}</section><details><summary>本地连读规则</summary>{r.readingGuide.map((line,i)=><p key={i}>{line}</p>)}</details></>;
  }
  const r=result as LiuyaoResult;
  return <><p className="wx-method-kicker">{r.calendar.localDate} · 月建 {r.calendar.monthBranch}{r.calendar.monthElement} · 日辰 {r.calendar.dayGanzhi} · {r.calendar.xun} · 旬空 {r.calendar.voidBranches.join('、')}</p><div className="wx-liuyao-diagrams"><LiuyaoDiagram result={r}/><span className="wx-hex-change" aria-hidden="true">→</span><LiuyaoDiagram result={r} changed/></div><p className="wx-liuyao-moving">{r.movingLines.length?`动爻：${r.movingLines.join('、')}`:'静卦 · 无动爻'} <span>○ 老阳动 · × 老阴动</span></p><p className="wx-method-caption">六亲以本卦{r.palace.name}宫{r.palace.element}为参照；本、变卦分别显示各自宫位与世应。</p><div className="wx-liuyao-table" role="region" aria-label="完整六爻装卦" tabIndex={0}><table><thead><tr><th>爻位</th><th>六神</th><th>六亲</th><th>本卦纳甲</th><th>爻象</th><th>世应/空</th><th>变卦</th></tr></thead><tbody>{[...r.lines].reverse().map(line=><tr key={line.position} data-moving={line.moving||undefined}><td>{line.position}</td><td>{line.spirit}</td><td>{line.relative}</td><td>{line.najia}{line.element}</td><td><span className="wx-table-line">{line.yinYang?'━━━':'━ ━'}</span> {line.label}{line.moving?<b className="wx-moving-mark">{line.yinYang?' ○动':' ×动'}</b>:null}</td><td>{line.role}{line.void?' 空':''}</td><td><span className="wx-table-line">{line.changed.yinYang?'━━━':'━ ━'}</span> {line.changed.relative} {line.changed.najia}{line.changed.element}{line.changed.role?` ${line.changed.role}`:''}{line.changed.void?' 空':''}</td></tr>)}</tbody></table></div><p className="wx-method-caption wx-table-hint">爻位由上至下排列；窄面板可横向滚动查看完整装卦。</p><details><summary>装卦过程、交节与规则约定</summary><ol>{r.steps.map((step,i)=><li key={i}>{step}</li>)}</ol><p>上一节：{r.calendar.previousJie.name} {r.calendar.previousJie.localTime}；下一节：{r.calendar.nextJie.name} {r.calendar.nextJie.localTime}</p>{r.conventions.map((line,i)=><p key={i}>{line}</p>)}</details></>;
}

export function formatMethodCopy(reading:MethodPageState['reading'],t:Translate){
  if(!reading)return '';
  const {moduleId,id,question,createdAt,environment,route,selectedRoute,wallTime,memory,status,coins,selectedSlots,result,text,conversation}=reading;
  return `${moduleInfo(moduleId).title}\n${JSON.stringify({id,question,createdAt,timeZone:environment.timeZone,wallTime,route:route??selectedRoute,backgroundUsage:memory,status,coins,selectedSlots,result},null,2)}\n${text}${formatConversationCopy(conversation,t)}`;
}

export function MethodPage(props:MethodPageProps){
  const {moduleId,state,memory,t}=props,{reading,draft,catalog}=state,info=moduleInfo(moduleId),copyText=methodCopy[moduleId],busy=readingIsBusy(reading),[copied,setCopied]=useState(false);
  const provider=catalog?.providers.find(value=>value.id===draft.route.provider),routeReady=!!provider?.models.some(model=>model.id===draft.route.model),unlocked=!!memory?.status?.unlocked;
  useEffect(()=>setCopied(false),[reading?.id]);
  const copy=async()=>{if(!reading)return;try{await navigator.clipboard.writeText(formatMethodCopy(reading,t));setCopied(true);}catch{setCopied(false);}};
  const status=reading?.status==='complete'?'完整解读':reading?.status==='cancelled'?'已取消，保留部分输出':reading?.status==='failed'?'解读未完成':'正在解读';
  return <section className={`wx-method-page wx-method-${moduleId}`} aria-label={info.title}><div className="wx-method-shell"><header className="wx-method-header"><div><p className="wx-method-kicker">{info.index} / {info.tradition}</p><h1>{info.title}<span className="wx-method-seal">{moduleId==='xiaoliu'?'六位':moduleId==='lenormand'?'小牌':'纳甲'}</span></h1><p className="wx-method-subtitle">{info.subtitle}</p><p className="wx-method-caption">{copyText.caption}</p></div><MethodArtwork id={moduleId}/></header>
    <div className="wx-method-workspace"><aside className="wx-method-input"><p className="wx-method-kicker">{copyText.input}</p><form className="wx-method-form" onSubmit={event=>{event.preventDefault();const wall=event.currentTarget.querySelector<HTMLInputElement>('input[type=datetime-local]');if(wall)props.onDraft({wallTime:wall.value});void props.onStart();}}><label htmlFor={`${moduleId}-question`}>所问之事</label><textarea id={`${moduleId}-question`} maxLength={500} rows={4} value={draft.question} disabled={busy||state.acting} onChange={event=>props.onDraft({question:event.target.value})} placeholder="写下本次的问题或背景"/><p className="wx-method-caption wx-question-count">{draft.question.length} / 500</p>
      {moduleId!=='lenormand'&&<><label htmlFor={`${moduleId}-time`}>指定时间</label><input id={`${moduleId}-time`} type="datetime-local" value={draft.wallTime} disabled={busy||state.acting} onChange={event=>props.onDraft({wallTime:event.target.value})} aria-describedby={`${moduleId}-time-hint`}/><p className="wx-method-caption" id={`${moduleId}-time-hint`}>可留空，使用起课当下。按 {catalog?.config.timeZone??'配置时区'} 的当地时间计算。</p></>}
      {moduleId==='lenormand'&&<><label htmlFor="lenormand-spread">排列</label><select id="lenormand-spread" value={draft.spreadId} disabled={busy||state.acting} onChange={event=>props.onDraft({spreadId:event.target.value})}><option value="line-3">三张连读</option><option value="line-5">五张对照</option></select><p className="wx-method-caption">无逆位；牌序、相邻组合与中牌共同组成含义。</p></>}
      {memory&&props.onOpenMemory&&<BackgroundControls state={memory} options={{useBackground:draft.useBackground,forOthers:draft.forOthers}} onChange={props.onDraft} onOpen={props.onOpenMemory} disabled={busy||state.acting||!memory.status} usage={reading?.memory}/>}
      <button className="wx-method-primary" type="submit" disabled={state.loading||state.acting||busy}>{state.loading?'正在读取本地状态':reading?'另起一轮':moduleId==='lenormand'?'洗牌，开始抽取':moduleId==='liuyao'?'开始六次投币':'本地起课'}<span aria-hidden="true">↗</span></button>
    </form><p className="wx-method-local-note">本地起课、抽牌与装卦无需模型；AI 解读沿用本轮已保存的结果。</p>{state.error&&<p className="wx-method-error" role="alert">{state.error}</p>}</aside>
    <div className="wx-method-output">{reading?<article className="wx-method-result"><header className="wx-reading-heading"><p className="wx-method-kicker">本轮所问</p><h2 className="wx-reading-question">{reading.question||'未填写问题'}</h2><p className="wx-method-caption">当地时间 {localTimestamp(reading.createdAt,reading.environment.timeZone).replace('T',' ')} · {reading.environment.timeZone}</p></header>
      {moduleId==='liuyao'&&reading.status==='collecting'&&<section className="wx-coin-ritual"><div className="wx-method-section-heading"><h2>自下而上 · 第 {reading.coins.length+1} 次</h2><span className="wx-method-badge">已记录 {reading.coins.length} / 6</span></div><p className="wx-method-caption">字面记2，背面记3；6老阴、7少阳、8少阴、9老阳。可模拟投币，或记录实物三币的和值。</p><div className="wx-coin-progress" aria-label={`投币进度：已记录 ${reading.coins.length} 爻`}>{Array.from({length:6},(_,i)=>{const coin=reading.coins[i];return <div key={i} className={`wx-coin-step${coin?' wx-coin-step-done':i===reading.coins.length?' wx-coin-step-current':''}`}><span>{i+1}爻</span><b>{coin?.value??'·'}</b><small>{coin?coin.value===6?'老阴':coin.value===7?'少阳':coin.value===8?'少阴':'老阳':i===reading.coins.length?'待投':'待续'}</small></div>;})}</div><ol className="wx-coin-records">{reading.coins.map((coin,i)=><li key={i}>第{i+1}爻：{coin.value} {coin.faces.length?`（${coin.faces.join('+')}）`:'（手动记录）'}</li>)}</ol><button className="wx-method-primary" disabled={state.acting} onClick={()=>void props.onLocal('toss')}>投掷三枚硬币 <span aria-hidden="true">↗</span></button><div className="wx-coin-values">{[6,7,8,9].map(value=><button key={value} disabled={state.acting} onClick={()=>void props.onLocal('record',{value})}>记录 {value}<small>{value===6?'老阴':value===7?'少阳':value===8?'少阴':'老阳'}</small></button>)}</div></section>}
      {moduleId==='lenormand'&&(reading.status==='selecting'||reading.status==='revealing')&&<section className="wx-card-ritual"><div className="wx-method-section-heading"><h2>{reading.status==='revealing'?'牌序已定，准备揭牌':`选择 ${reading.selectionCount} 张背牌`}</h2><span className="wx-method-badge">已选 {reading.selectedSlots.length} / {reading.selectionCount}</span></div><p className="wx-method-caption">顺序就是牌序，选取后保留本轮排列。</p><div className="wx-selection-progress" aria-label="已选牌序">{Array.from({length:reading.selectionCount},(_,i)=><span key={i} className={reading.selectedSlots[i]?'wx-selection-filled':''}>{i+1}<small>{reading.selectedSlots[i]?'已选':'待选'}</small></span>)}</div>{reading.status==='selecting'&&<div className="wx-small-deck" aria-label="36张雷诺曼背牌">{Array.from({length:36},(_,i)=><button key={i} disabled={state.acting||reading.selectedSlots.includes(i+1)} className={reading.selectedSlots.includes(i+1)?'wx-deck-selected':''} aria-label={`选择第 ${i+1} 张背牌`} onClick={()=>void props.onLocal('select',{slot:i+1})}>{reading.selectedSlots.includes(i+1)?<><span>已选</span><b>{reading.selectedSlots.indexOf(i+1)+1}</b></>:<span className="wx-deck-sprig" aria-hidden="true">❧</span>}</button>)}</div>}</section>}
      {reading.status==='revealing'&&<button className="wx-method-primary" disabled={state.acting} onClick={()=>void props.onLocal('reveal')}>揭示这组牌 <span aria-hidden="true">↗</span></button>}
      {reading.result!==null&&<MethodResult id={moduleId} result={reading.result}/>}
      {reading.status==='ready'&&<section className="wx-method-ai"><div className="wx-method-section-heading"><h2>解读本次结果</h2><span className="wx-method-badge">AI 解读</span></div><p className="wx-method-caption">使用 DSH 已配置的模型，将本地结果与本轮背景选择交给供应商解读。</p><div className="wx-method-model-row"><label htmlFor={`${moduleId}-provider`}>供应商<select id={`${moduleId}-provider`} value={draft.route.provider} disabled={state.acting||!catalog?.providers.length} onChange={event=>{const selected=catalog?.providers.find(p=>p.id===event.target.value);props.onDraft({route:{provider:event.target.value,model:selected?.models[0]?.id??''}});}}>{catalog?.providers.length?catalog.providers.map(p=><option key={p.id} value={p.id}>{p.name}</option>):<option value="">没有可用供应商</option>}</select></label><label htmlFor={`${moduleId}-model`}>模型<select id={`${moduleId}-model`} value={draft.route.model} disabled={state.acting||!provider?.models.length} onChange={event=>props.onDraft({route:{...draft.route,model:event.target.value}})}>{provider?.models.length?provider.models.map(m=><option key={m.id} value={m.id}>{m.name}</option>):<option value="">没有可选模型</option>}</select></label></div>
        {!catalog?.providers.length&&<p className="wx-method-notice">还没有可用的模型，请先在 DSH 设置中配置供应商，再刷新模型目录。本地结果已保留。</p>}{provider&&!provider.models.length&&<p className="wx-method-notice">当前供应商没有可选模型，请检查供应商配置或选择其他供应商。</p>}{provider?.error&&<p className="wx-method-notice" role="alert">{provider.error}</p>}
        {!unlocked&&<p className="wx-method-notice">{!memory?.status?'正在读取共享背景状态。':memory.status.initialized?'共享背景已锁定。AI 解读前需解锁。':'AI 解读前需为共享背景设置独立口令。'}{props.onOpenMemory&&memory?.status&&<button className="wx-method-text-button" onClick={props.onOpenMemory}>{memory.status.initialized?'解锁共享背景':'设置独立口令'}</button>}本地计算与抽牌可继续。</p>}
        {memory?.status?.updating&&<p className="wx-method-caption" role="status">背景正在更新，解读会等待更新结束。</p>}<div className="wx-method-actions"><button className="wx-method-primary" disabled={state.acting||!routeReady||!unlocked} onClick={()=>void props.onInterpret()}>{state.acting?'正在提交':'开始解读'} <span aria-hidden="true">↗</span></button><button disabled={state.acting} onClick={()=>void props.onRefresh()}>刷新模型目录</button></div></section>}
      {(reading.text||reading.status==='streaming')&&<section className="wx-method-interpretation"><div className="wx-method-section-heading"><h2>本轮解读</h2><p className={`wx-method-reading-status wx-method-status-${reading.status}`} role="status">{status} · 背景 {reading.memory?.enabled?`v${reading.memory.revision}`:'停用'}</p></div><div className="wx-method-text">{reading.text?reading.text.split('\n').map((line,i)=><p key={i}>{line||'\u00a0'}</p>):<p className="wx-method-caption">解读将在这里徐徐展开。</p>}</div>{reading.status==='streaming'&&<button disabled={state.acting} onClick={()=>void props.onCancel()}>取消解读</button>}</section>}
      {reading.error&&<p className="wx-method-error" role="alert">{reading.error.message}</p>}
      {reading.text&&reading.status!=='streaming'&&<Conversation key={reading.id} readingId={reading.id} turns={reading.conversation??[]} busy={busy} pending={state.acting||!unlocked} draft={draft.followupQuestion} theme={moduleId} t={t} onDraftChange={followupQuestion=>props.onDraft({followupQuestion})} onSend={props.onFollowup} onCancel={async()=>{await props.onCancel();}}/>}
      <div className="wx-method-actions wx-method-end-actions"><button onClick={()=>void copy()}>复制结果{copied?' · 已复制':''}</button><button disabled={busy||state.acting||!unlocked||memory?.status?.updating} onClick={()=>void props.onCheckpoint()}>结束本轮并更新背景</button>{reading.memory?.forOthers&&<p className="wx-method-caption">替他人占卜，不写入本人记忆。</p>}</div>
    </article>:<section className="wx-method-empty" aria-label={`${info.title}结果说明`}><MethodArtwork id={moduleId}/><p className="wx-method-kicker">{state.loading?'正在读取本地状态':'本地结果 · 等待开始'}</p><h2>{copyText.empty}</h2><p>{copyText.description}</p><ol>{copyText.steps.map((step,i)=><li key={step}><span>{String(i+1).padStart(2,'0')}</span>{step}</li>)}</ol></section>}</div></div>
    <footer>本地规则计算与牌义不调用模型 · 供娱乐与自省</footer></div></section>;
}
